x-default-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
  driver: json-file


include:
  - ./docker-compose-jaeger.yml


services:

  nginx:
    image: nginx:1.23.2
    container_name: Nginx
    logging: *default-logging
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common_network
    ports:
      - "80:80"

  auth_service:
    build:
      context: ./auth_service
    container_name: AuthService
    logging: *default-logging
    depends_on:
      - redis
      - db
    volumes:
      - ./auth_service/src:/opt/src
    networks:
      - common_network
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: Auth_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_SERVICE_DB_USER} -d ${AUTH_SERVICE_DB_NAME}" ]
      interval: 1s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - common_network

  redis:
    image: "redis:7.2.3-bookworm"
    container_name: Redis
    logging: *default-logging
    networks:
      - common_network
    env_file:
      - .env

networks:
  common_network:
    driver: bridge

volumes:
  postgres_volume:
