version: '3.9'

x-default-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
  driver: json-file


services:

  nginx:
    image: nginx:1.23.2
    container_name: Nginx
    logging: *default-logging
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common_network
    ports:
      - "80:80"

  auth_service:
    image: auth2
    logging: *default-logging
    depends_on:
      - redis
      - db
    volumes:
      - ./auth_service/src:/opt/src
    networks:
      - common_network
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_NAME=${AUTH_SERVICE_NAME}
      - AUTH_SERVICE_OPENAPI_URL=${AUTH_SERVICE_OPENAPI_URL}
      - AUTH_SERVICE_DOCS_URL=${AUTH_SERVICE_DOCS_URL}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_SERVICE_WORKERS=${AUTH_SERVICE_WORKERS}
      - AUTH_SERVICE_LOG_LEVEL=${AUTH_SERVICE_LOG_LEVEL}
      - AUTH_SERVICE_DB_HOST=${AUTH_SERVICE_DB_HOST}
      - AUTH_SERVICE_DB_PORT=${AUTH_SERVICE_DB_PORT}
      - AUTH_SERVICE_DB_NAME=${AUTH_SERVICE_DB_NAME}
      - AUTH_SERVICE_DB_USER=${AUTH_SERVICE_DB_USER}
      - AUTH_SERVICE_DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}

  db:
    image: postgres:14-alpine
    container_name: Auth_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_SERVICE_DB_USER} -d ${AUTH_SERVICE_DB_NAME}" ]
      interval: 1s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - common_network
    ports:
      - "5432:5432"

  redis:
    image: "redis:7.2.3-bookworm"
    container_name: Redis
    logging: *default-logging
    networks:
      - common_network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CONNECTION_TIMEOUT=${REDIS_CONNECTION_TIMEOUT}

networks:
  common_network:

volumes:
  postgres_volume:
