name: deploy-auth2

on: 
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "auth_service"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "./auth_service"
          file: "auth_service/Dockerfile"
          push: true
          tags: "arigatory/moviepoisk-auth2:latest"

