name: Pylint

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.1.1
        pip install autoflake==2.2.1
        pip install flake8==7.0.0
    - name: Check code with black
      run: black --line-length=120 .
    - name: Check code with flake 8
      run: flake8 --max-line-length=120 --ignore=D100,D101,D104,D105,D106,D107,E231,D210,W605 .
    - name: Remove unused import with autoflake
      run: autoflake --remove-all-unused-imports --verbose --recursive --in-place .
